"""added nullable=True in template hidden column

Revision ID: 2bc43939f172
Revises: 6f54b09a6fd1
Create Date: 2025-09-26 13:15:56.581137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bc43939f172'
down_revision: Union[str, Sequence[str], None] = '6f54b09a6fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')
    op.drop_table('arena_rating')
    op.drop_table('arena_ranking')
    op.add_column('arena_challenge', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'arena_challenge', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'arena_challenge', 'text_category', ['text_category_id'], ['id'])
    op.add_column('battle_result', sa.Column('voter_user_id', sa.String(), nullable=True))
    op.add_column('battle_result', sa.Column('winner_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'battle_result', 'template_v2', ['template_A_id'], ['id'])
    op.create_foreign_key(None, 'battle_result', 'template_v2', ['template_B_id'], ['id'])
    op.create_foreign_key(None, 'battle_result', 'arena_challenge', ['challenge_id'], ['id'])
    op.create_foreign_key(None, 'battle_result', 'user', ['voter_user_id'], ['id'])
    op.drop_column('battle_result', 'winner_id')
    op.drop_constraint(op.f('elo_rating_by_model_model_name_key'), 'elo_rating_by_model', type_='unique')
    op.create_foreign_key(None, 'elo_rating_by_model', 'arena_challenge', ['challenge_id'], ['id'])
    op.create_unique_constraint('_model_template_challenge_uc', 'elo_rating_by_model_and_template', ['model_name', 'template_id', 'challenge_id'])
    op.create_foreign_key(None, 'elo_rating_by_model_and_template', 'template_v2', ['template_id'], ['id'])
    op.create_foreign_key(None, 'elo_rating_by_model_and_template', 'arena_challenge', ['challenge_id'], ['id'])
    op.drop_constraint(op.f('elo_rating_by_template_template_id_key'), 'elo_rating_by_template', type_='unique')
    op.create_foreign_key(None, 'elo_rating_by_template', 'arena_challenge', ['challenge_id'], ['id'])
    op.create_foreign_key(None, 'elo_rating_by_template', 'template_v2', ['template_id'], ['id'])
    op.alter_column('template_v2', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'template_v2', 'arena_challenge', ['challenge_id'], ['id'])
    op.create_foreign_key(None, 'template_v2', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_v2', type_='foreignkey')
    op.drop_constraint(None, 'template_v2', type_='foreignkey')
    op.alter_column('template_v2', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'elo_rating_by_template', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_template', type_='foreignkey')
    op.create_unique_constraint(op.f('elo_rating_by_template_template_id_key'), 'elo_rating_by_template', ['template_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='foreignkey')
    op.drop_constraint('_model_template_challenge_uc', 'elo_rating_by_model_and_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model', type_='foreignkey')
    op.create_unique_constraint(op.f('elo_rating_by_model_model_name_key'), 'elo_rating_by_model', ['model_name'], postgresql_nulls_not_distinct=False)
    op.add_column('battle_result', sa.Column('winner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_column('battle_result', 'winner_status')
    op.drop_column('battle_result', 'voter_user_id')
    op.drop_constraint(None, 'arena_challenge', type_='foreignkey')
    op.drop_constraint(None, 'arena_challenge', type_='foreignkey')
    op.drop_column('arena_challenge', 'user_id')
    op.create_table('arena_ranking',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('challenge_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('arena_ranking_pkey'))
    )
    op.create_table('arena_rating',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('arena_rating_pkey'))
    )
    op.create_table('template',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('template_pkey'))
    )
    # ### end Alembic commands ###
