"""add_comment_column_to_vote_table

Revision ID: 5924870362e5
Revises: 13b1003da99f
Create Date: 2025-09-10 12:34:45.522742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5924870362e5'
down_revision: Union[str, Sequence[str], None] = '13b1003da99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'comment')
    # ### end Alembic commands ###
