"""create room table

Revision ID: 5b70d46206c7
Revises: 65735e75bac9
Create Date: 2025-10-27 15:37:38.883700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b70d46206c7'
down_revision: Union[str, Sequence[str], None] = '65735e75bac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')
    op.create_unique_constraint(None, 'arena_challenge', ['id'])
    op.create_unique_constraint(None, 'battle_result', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'challenge', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_model', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_model_and_template', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_template', ['id'])
    op.create_index(op.f('ix_model_created_by'), 'model', ['created_by'], unique=False)
    op.create_index(op.f('ix_model_updated_by'), 'model', ['updated_by'], unique=False)
    op.create_unique_constraint(None, 'model', ['id'])
    op.create_foreign_key(None, 'model', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'model', 'user', ['created_by'], ['id'])
    op.create_unique_constraint(None, 'model_version', ['id'])
    op.create_unique_constraint(None, 'result', ['id'])
    op.create_unique_constraint(None, 'submission', ['id'])
    op.create_unique_constraint(None, 'template_v2', ['id'])
    op.create_unique_constraint(None, 'text_category', ['id'])
    op.create_unique_constraint(None, 'translation_job', ['id'])
    op.create_unique_constraint(None, 'translation_output', ['id'])
    op.create_unique_constraint(None, 'vote', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='unique')
    op.drop_constraint(None, 'translation_output', type_='unique')
    op.drop_constraint(None, 'translation_job', type_='unique')
    op.drop_constraint(None, 'text_category', type_='unique')
    op.drop_constraint(None, 'template_v2', type_='unique')
    op.drop_constraint(None, 'submission', type_='unique')
    op.drop_constraint(None, 'result', type_='unique')
    op.drop_constraint(None, 'model_version', type_='unique')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_constraint(None, 'model', type_='unique')
    op.drop_index(op.f('ix_model_updated_by'), table_name='model')
    op.drop_index(op.f('ix_model_created_by'), table_name='model')
    op.drop_constraint(None, 'elo_rating_by_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model', type_='unique')
    op.drop_constraint(None, 'challenge', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'battle_result', type_='unique')
    op.drop_constraint(None, 'arena_challenge', type_='unique')
    op.create_table('template',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='template_pkey')
    )
    # ### end Alembic commands ###
