"""update_template_v2_add_user_id_foreign_key

Revision ID: 6080d246c112
Revises: ae9062696746
Create Date: 2025-09-24 19:40:52.806086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6080d246c112'
down_revision: Union[str, Sequence[str], None] = 'ae9062696746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check table existence before performing operations
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # Handle arena_rating table drop (if exists)
    if 'arena_rating' in existing_tables:
        op.drop_table('arena_rating')
    
    # Handle arena_challenge table operations (if exists)
    if 'arena_challenge' in existing_tables:
        op.add_column('arena_challenge', sa.Column('user_id', sa.String(), nullable=False))
        op.create_unique_constraint(None, 'arena_challenge', ['id'])
        op.create_foreign_key(None, 'arena_challenge', 'text_category', ['text_category_id'], ['id'])
        op.create_foreign_key(None, 'arena_challenge', 'user', ['user_id'], ['id'])
    
    # Handle arena_ranking table operations (if exists)
    if 'arena_ranking' in existing_tables:
        op.create_unique_constraint(None, 'arena_ranking', ['id'])
    
    # Handle battle_result table operations (if exists)
    if 'battle_result' in existing_tables:
        op.add_column('battle_result', sa.Column('voter_user_id', sa.String(), nullable=True))
        op.add_column('battle_result', sa.Column('winner_status', sa.String(), nullable=True))
        op.create_unique_constraint(None, 'battle_result', ['id'])
        op.create_foreign_key(None, 'battle_result', 'template_v2', ['template_B_id'], ['id'])
        op.create_foreign_key(None, 'battle_result', 'user', ['voter_user_id'], ['id'])
        op.create_foreign_key(None, 'battle_result', 'arena_challenge', ['challenge_id'], ['id'])
        op.create_foreign_key(None, 'battle_result', 'template_v2', ['template_A_id'], ['id'])
        op.drop_column('battle_result', 'winner_id')
    
    # Handle elo_rating_by_model table operations (if exists)
    if 'elo_rating_by_model' in existing_tables:
        try:
            op.drop_constraint(op.f('elo_rating_by_model_model_name_key'), 'elo_rating_by_model', type_='unique')
        except Exception:
            pass  # Constraint might not exist
        op.create_unique_constraint(None, 'elo_rating_by_model', ['id'])
        op.create_foreign_key(None, 'elo_rating_by_model', 'arena_challenge', ['challenge_id'], ['id'])
    
    # Handle elo_rating_by_model_and_template table operations (if exists)
    if 'elo_rating_by_model_and_template' in existing_tables:
        op.create_unique_constraint('_model_template_challenge_uc', 'elo_rating_by_model_and_template', ['model_name', 'template_id', 'challenge_id'])
        op.create_unique_constraint(None, 'elo_rating_by_model_and_template', ['id'])
        op.create_foreign_key(None, 'elo_rating_by_model_and_template', 'arena_challenge', ['challenge_id'], ['id'])
        op.create_foreign_key(None, 'elo_rating_by_model_and_template', 'template_v2', ['template_id'], ['id'])
    
    # Handle elo_rating_by_template table operations (if exists)
    if 'elo_rating_by_template' in existing_tables:
        try:
            op.drop_constraint(op.f('elo_rating_by_template_template_id_key'), 'elo_rating_by_template', type_='unique')
        except Exception:
            pass  # Constraint might not exist
        op.create_unique_constraint(None, 'elo_rating_by_template', ['id'])
        op.create_foreign_key(None, 'elo_rating_by_template', 'template_v2', ['template_id'], ['id'])
        op.create_foreign_key(None, 'elo_rating_by_template', 'arena_challenge', ['challenge_id'], ['id'])
    
    # Handle model_version table operations (if exists)
    if 'model_version' in existing_tables:
        op.alter_column('model_version', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.DateTime(),
                   existing_nullable=False,
                   existing_server_default=sa.text('now()'))
        try:
            op.drop_index(op.f('idx_model_version_vote_count'), table_name='model_version')
        except Exception:
            pass  # Index might not exist
    
    # Handle template table operations (if exists)
    if 'template' in existing_tables:
        op.create_unique_constraint(None, 'template', ['id'])
    
    # Handle template_v2 table operations (if exists)
    if 'template_v2' in existing_tables:
        op.create_unique_constraint(None, 'template_v2', ['id'])
        op.create_foreign_key(None, 'template_v2', 'arena_challenge', ['challenge_id'], ['id'])
        op.create_foreign_key(None, 'template_v2', 'user', ['user_id'], ['id'])
    
    # Handle text_category table operations (if exists)
    if 'text_category' in existing_tables:
        op.create_unique_constraint(None, 'text_category', ['id'])
    
    # Handle translation_job table operations (if exists)
    if 'translation_job' in existing_tables:
        op.alter_column('translation_job', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.DateTime(),
                   existing_nullable=False,
                   existing_server_default=sa.text('now()'))
        try:
            op.drop_index(op.f('idx_translation_job_user_id'), table_name='translation_job')
        except Exception:
            pass  # Index might not exist
    
    # Handle translation_output table operations (if exists)
    if 'translation_output' in existing_tables:
        op.alter_column('translation_output', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.DateTime(),
                   existing_nullable=False,
                   existing_server_default=sa.text('now()'))
        try:
            op.drop_index(op.f('idx_translation_output_job_id'), table_name='translation_output')
        except Exception:
            pass  # Index might not exist
        try:
            op.drop_index(op.f('idx_translation_output_model_version_id'), table_name='translation_output')
        except Exception:
            pass  # Index might not exist
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_translation_output_model_version_id'), 'translation_output', ['model_version_id'], unique=False)
    op.create_index(op.f('idx_translation_output_job_id'), 'translation_output', ['job_id'], unique=False)
    op.alter_column('translation_output', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_translation_job_user_id'), 'translation_job', ['user_id'], unique=False)
    op.alter_column('translation_job', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'text_category', type_='unique')
    op.drop_constraint(None, 'template_v2', type_='foreignkey')
    op.drop_constraint(None, 'template_v2', type_='foreignkey')
    op.drop_constraint(None, 'template_v2', type_='unique')
    op.drop_constraint(None, 'template', type_='unique')
    op.create_index(op.f('idx_model_version_vote_count'), 'model_version', ['vote_count'], unique=False)
    op.alter_column('model_version', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'elo_rating_by_template', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_template', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_template', type_='unique')
    op.create_unique_constraint(op.f('elo_rating_by_template_template_id_key'), 'elo_rating_by_template', ['template_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='unique')
    op.drop_constraint('_model_template_challenge_uc', 'elo_rating_by_model_and_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model', type_='foreignkey')
    op.drop_constraint(None, 'elo_rating_by_model', type_='unique')
    op.create_unique_constraint(op.f('elo_rating_by_model_model_name_key'), 'elo_rating_by_model', ['model_name'], postgresql_nulls_not_distinct=False)
    op.add_column('battle_result', sa.Column('winner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='foreignkey')
    op.drop_constraint(None, 'battle_result', type_='unique')
    op.drop_column('battle_result', 'winner_status')
    op.drop_column('battle_result', 'voter_user_id')
    op.drop_constraint(None, 'arena_ranking', type_='unique')
    op.drop_constraint(None, 'arena_challenge', type_='foreignkey')
    op.drop_constraint(None, 'arena_challenge', type_='foreignkey')
    op.drop_constraint(None, 'arena_challenge', type_='unique')
    op.drop_column('arena_challenge', 'user_id')
    op.create_table('arena_rating',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('arena_rating_pkey'))
    )
    # ### end Alembic commands ###
