"""update_models_with_user_foreign_keys

Revision ID: 611e22ed1f2a
Revises: 6080d246c112
Create Date: 2025-09-24 19:57:04.637916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611e22ed1f2a'
down_revision: Union[str, Sequence[str], None] = '6080d246c112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'arena_challenge', ['id'])
    op.create_unique_constraint(None, 'arena_ranking', ['id'])
    op.create_unique_constraint(None, 'battle_result', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_model', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_model_and_template', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_template', ['id'])
    op.create_index(op.f('ix_model_created_by'), 'model', ['created_by'], unique=False)
    op.create_index(op.f('ix_model_updated_by'), 'model', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'model', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'model', 'user', ['created_by'], ['id'])
    op.add_column('template', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_template_user_id'), 'template', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'template', ['id'])
    op.create_foreign_key(None, 'template', 'user', ['user_id'], ['id'])
    op.drop_column('template', 'username')
    op.create_unique_constraint(None, 'template_v2', ['id'])
    op.create_unique_constraint(None, 'text_category', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_category', type_='unique')
    op.drop_constraint(None, 'template_v2', type_='unique')
    op.add_column('template', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.drop_constraint(None, 'template', type_='unique')
    op.drop_index(op.f('ix_template_user_id'), table_name='template')
    op.drop_column('template', 'user_id')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_index(op.f('ix_model_updated_by'), table_name='model')
    op.drop_index(op.f('ix_model_created_by'), table_name='model')
    op.drop_constraint(None, 'elo_rating_by_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model', type_='unique')
    op.drop_constraint(None, 'battle_result', type_='unique')
    op.drop_constraint(None, 'arena_ranking', type_='unique')
    op.drop_constraint(None, 'arena_challenge', type_='unique')
    # ### end Alembic commands ###
