"""add is_zero_shot field

Revision ID: 65735e75bac9
Revises: cd97760834ce
Create Date: 2025-10-23 10:42:07.710131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65735e75bac9'
down_revision: Union[str, Sequence[str], None] = 'cd97760834ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column without default (instant)
   op.add_column('template_v2', sa.Column('is_zero_shot', sa.Boolean(), nullable=True, server_default='false'))
   
   
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'is_zero_shot')
    
    # ### end Alembic commands ###
