"""auto migration

Revision ID: 6f54b09a6fd1
Revises: 60eeb591cf72
Create Date: 2025-09-26 12:54:43.395439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f54b09a6fd1'
down_revision: Union[str, Sequence[str], None] = '60eeb591cf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_v2', sa.Column('hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'hidden')
    # ### end Alembic commands ###
