"""add_user_foreign_keys_to_translation_job_and_vote

Revision ID: 7ebcddc81423
Revises: e6c8d09f17be
Create Date: 2025-09-10 11:54:37.082467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ebcddc81423'
down_revision: Union[str, Sequence[str], None] = 'e6c8d09f17be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if vote_count column exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('model_version')]
    
    if 'vote_count' not in columns:
        op.add_column('model_version', sa.Column('vote_count', sa.Integer(), nullable=False, server_default='0'))
    
    # Create constraints with error handling
    try:
        op.create_unique_constraint(None, 'model_version', ['id'])
    except Exception as e:
        print(f"Constraint on model_version.id may already exist: {e}")
    
    try:
        op.create_unique_constraint(None, 'translation_job', ['id'])
    except Exception as e:
        print(f"Constraint on translation_job.id may already exist: {e}")
    
    try:
        op.create_foreign_key(None, 'translation_job', 'user', ['user_id'], ['id'])
    except Exception as e:
        print(f"Foreign key on translation_job.user_id may already exist: {e}")
    
    try:
        op.create_unique_constraint(None, 'translation_output', ['id'])
    except Exception as e:
        print(f"Constraint on translation_output.id may already exist: {e}")
    op.alter_column('vote', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vote', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # Drop indexes with error handling
    try:
        op.drop_index('idx_vote_comparison_pair', table_name='vote')
    except Exception as e:
        print(f"Index idx_vote_comparison_pair may not exist: {e}")
    
    try:
        op.drop_index('idx_vote_created_at_analytics', table_name='vote')
    except Exception as e:
        print(f"Index idx_vote_created_at_analytics may not exist: {e}")
    
    try:
        op.drop_index('idx_vote_is_tie', table_name='vote')
    except Exception as e:
        print(f"Index idx_vote_is_tie may not exist: {e}")
    
    try:
        op.drop_index('idx_vote_translation_job_id', table_name='vote')
    except Exception as e:
        print(f"Index idx_vote_translation_job_id may not exist: {e}")
    
    try:
        op.drop_index('idx_vote_user_id_analytics', table_name='vote')
    except Exception as e:
        print(f"Index idx_vote_user_id_analytics may not exist: {e}")
    
    try:
        op.drop_index('idx_vote_winner_id', table_name='vote')
    except Exception as e:
        print(f"Index idx_vote_winner_id may not exist: {e}")
    
    try:
        op.create_unique_constraint(None, 'vote', ['id'])
    except Exception as e:
        print(f"Constraint on vote.id may already exist: {e}")
    
    # Drop old foreign key constraints with error handling
    try:
        op.drop_constraint('fk_vote_translation_output_b', 'vote', type_='foreignkey')
    except Exception as e:
        print(f"Constraint fk_vote_translation_output_b may not exist: {e}")
    
    try:
        op.drop_constraint('fk_vote_winner', 'vote', type_='foreignkey')
    except Exception as e:
        print(f"Constraint fk_vote_winner may not exist: {e}")
    
    try:
        op.drop_constraint('fk_vote_translation_output_a', 'vote', type_='foreignkey')
    except Exception as e:
        print(f"Constraint fk_vote_translation_output_a may not exist: {e}")
    
    try:
        op.drop_constraint('fk_vote_translation_job', 'vote', type_='foreignkey')
    except Exception as e:
        print(f"Constraint fk_vote_translation_job may not exist: {e}")
    
    # Create new foreign key constraints with error handling
    try:
        op.create_foreign_key(None, 'vote', 'translation_output', ['translation_output_b_id'], ['id'])
    except Exception as e:
        print(f"Foreign key on vote.translation_output_b_id may already exist: {e}")
    
    try:
        op.create_foreign_key(None, 'vote', 'user', ['user_id'], ['id'])
    except Exception as e:
        print(f"Foreign key on vote.user_id may already exist: {e}")
    
    try:
        op.create_foreign_key(None, 'vote', 'translation_output', ['translation_output_a_id'], ['id'])
    except Exception as e:
        print(f"Foreign key on vote.translation_output_a_id may already exist: {e}")
    
    try:
        op.create_foreign_key(None, 'vote', 'translation_output', ['winner_id'], ['id'])
    except Exception as e:
        print(f"Foreign key on vote.winner_id may already exist: {e}")
    
    try:
        op.create_foreign_key(None, 'vote', 'translation_job', ['translation_job_id'], ['id'])
    except Exception as e:
        print(f"Foreign key on vote.translation_job_id may already exist: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key('fk_vote_translation_job', 'vote', 'translation_job', ['translation_job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_vote_translation_output_a', 'vote', 'translation_output', ['translation_output_a_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_vote_winner', 'vote', 'translation_output', ['winner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_vote_translation_output_b', 'vote', 'translation_output', ['translation_output_b_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vote', type_='unique')
    op.create_index('idx_vote_winner_id', 'vote', ['winner_id'], unique=False)
    op.create_index('idx_vote_user_id_analytics', 'vote', ['user_id'], unique=False)
    op.create_index('idx_vote_translation_job_id', 'vote', ['translation_job_id'], unique=False)
    op.create_index('idx_vote_is_tie', 'vote', ['is_tie'], unique=False)
    op.create_index('idx_vote_created_at_analytics', 'vote', ['created_at'], unique=False)
    op.create_index('idx_vote_comparison_pair', 'vote', ['translation_output_a_id', 'translation_output_b_id'], unique=False)
    op.alter_column('vote', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vote', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'translation_output', type_='unique')
    op.drop_constraint(None, 'translation_job', type_='foreignkey')
    op.drop_constraint(None, 'translation_job', type_='unique')
    op.drop_constraint(None, 'model_version', type_='unique')
    
    # Check if vote_count column exists before dropping it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('model_version')]
    
    if 'vote_count' in columns:
        op.drop_column('model_version', 'vote_count')
    # ### end Alembic commands ###
