"""remove input and output text from elo rating tables

Revision ID: cd97760834ce
Revises: 623f4f1f9496
Create Date: 2025-09-30 16:30:53.982467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd97760834ce'
down_revision: Union[str, Sequence[str], None] = '623f4f1f9496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elo_rating_by_model', 'input_text')
    op.drop_column('elo_rating_by_model', 'output_text')
    op.drop_column('elo_rating_by_model_and_template', 'input_text')
    op.drop_column('elo_rating_by_model_and_template', 'output_text')
    op.drop_column('elo_rating_by_template', 'input_text')
    op.drop_column('elo_rating_by_template', 'output_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elo_rating_by_template', sa.Column('output_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('elo_rating_by_template', sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('elo_rating_by_model_and_template', sa.Column('output_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('elo_rating_by_model_and_template', sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('elo_rating_by_model', sa.Column('output_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('elo_rating_by_model', sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
