"""added constraint in arena rating table

Revision ID: dfac7c2a7644
Revises: f7913bd92de3
Create Date: 2025-09-25 10:39:34.474929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfac7c2a7644'
down_revision: Union[str, Sequence[str], None] = 'f7913bd92de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'arena_challenge', ['id'])
    op.create_unique_constraint(None, 'battle_result', ['id'])
    op.create_unique_constraint('_model_challenge_uc', 'elo_rating_by_model', ['model_name', 'challenge_id'])
    op.create_unique_constraint(None, 'elo_rating_by_model', ['id'])
    op.create_unique_constraint(None, 'elo_rating_by_model_and_template', ['id'])
    op.create_unique_constraint('_template_challenge_uc', 'elo_rating_by_template', ['template_id', 'challenge_id'])
    op.create_unique_constraint(None, 'elo_rating_by_template', ['id'])
    op.create_index(op.f('ix_model_created_by'), 'model', ['created_by'], unique=False)
    op.create_index(op.f('ix_model_updated_by'), 'model', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'model', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'model', 'user', ['updated_by'], ['id'])
    op.alter_column('model_version', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_model_version_vote_count', table_name='model_version')
    op.create_unique_constraint(None, 'template_v2', ['id'])
    op.create_unique_constraint(None, 'text_category', ['id'])
    op.alter_column('translation_job', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_translation_job_user_id', table_name='translation_job')
    op.alter_column('translation_output', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_translation_output_job_id', table_name='translation_output')
    op.drop_index('idx_translation_output_model_version_id', table_name='translation_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_translation_output_model_version_id', 'translation_output', ['model_version_id'], unique=False)
    op.create_index('idx_translation_output_job_id', 'translation_output', ['job_id'], unique=False)
    op.alter_column('translation_output', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_translation_job_user_id', 'translation_job', ['user_id'], unique=False)
    op.alter_column('translation_job', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'text_category', type_='unique')
    op.drop_constraint(None, 'template_v2', type_='unique')
    op.create_index('idx_model_version_vote_count', 'model_version', ['vote_count'], unique=False)
    op.alter_column('model_version', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_index(op.f('ix_model_updated_by'), table_name='model')
    op.drop_index(op.f('ix_model_created_by'), table_name='model')
    op.drop_constraint(None, 'elo_rating_by_template', type_='unique')
    op.drop_constraint('_template_challenge_uc', 'elo_rating_by_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model_and_template', type_='unique')
    op.drop_constraint(None, 'elo_rating_by_model', type_='unique')
    op.drop_constraint('_model_challenge_uc', 'elo_rating_by_model', type_='unique')
    op.drop_constraint(None, 'battle_result', type_='unique')
    op.drop_constraint(None, 'arena_challenge', type_='unique')
    # ### end Alembic commands ###
