"""initialize

Revision ID: f7913bd92de3
Revises: 
Create Date: 2025-09-24 20:42:32.668286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7913bd92de3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_challenge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text_category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('challenge_name', sa.String(), nullable=False),
    sa.Column('from_language', sa.String(), nullable=False),
    sa.Column('to_language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['text_category_id'], ['text_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('elo_rating_by_model',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['arena_challenge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('template_v2',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['arena_challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('battle_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_A_id', sa.String(), nullable=False),
    sa.Column('template_B_id', sa.String(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('output_text_A', sa.String(), nullable=True),
    sa.Column('output_text_B', sa.String(), nullable=True),
    sa.Column('model_A', sa.String(), nullable=False),
    sa.Column('model_B', sa.String(), nullable=False),
    sa.Column('voter_user_id', sa.String(), nullable=True),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('winner_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['arena_challenge.id'], ),
    sa.ForeignKeyConstraint(['template_A_id'], ['template_v2.id'], ),
    sa.ForeignKeyConstraint(['template_B_id'], ['template_v2.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('elo_rating_by_model_and_template',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['arena_challenge.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model_name', 'template_id', 'challenge_id', name='_model_template_challenge_uc')
    )
    op.create_table('elo_rating_by_template',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['arena_challenge.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elo_rating_by_template')
    op.drop_table('elo_rating_by_model_and_template')
    op.drop_table('battle_result')
    op.drop_table('template_v2')
    op.drop_table('elo_rating_by_model')
    op.drop_table('arena_challenge')
    # ### end Alembic commands ###
